### Crear usuario
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "nombre": "Nicolas",
    "email": "nicolas@fittrack.com",
    "contrasena": "12345678",
    "fechaRegistro": "2026-08-04"
}
